---
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "consul-server"
  namespace: "default"
  labels:
    app: "consul-server"
spec:
  serviceName: "consul-server"
  replicas: 1
  template:
    metadata:
      labels:
        app: "consul-server"
    spec:
      containers:
      - name: "consul"
        image: "consul"
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CONSUL_LOCAL_CONFIG"
          value:
            "{
              \"server\": true,
              \"bind_addr\": \"$(MY_POD_IP)\",
              \"client_addr\": \"$(MY_POD_IP)\",
              \"data_dir\": \"/consul/data\",
              \"ui\": true,
              \"advertise_addr\": \"$(MY_POD_IP)\"
            }"
        ports:
        - containerPort: 8500
          name: ui-port
        - containerPort: 8400
          name: alt-port
        - containerPort: 53
          name: udp-port
        - containerPort: 8443
          name: https-port
        - containerPort: 8080
          name: http-port
        - containerPort: 8301
          name: serflan
        - containerPort: 8302
          name: serfwan
        - containerPort: 8600
          name: consuldns
        - containerPort: 8300
          name: server
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "consul-service"
  namespace: "default"
  labels:
    app: "consul-server"
spec:
  ports:
  - name: ui
    protocol: "TCP"
    port: 8500
  - name: dns
    protocol: "TCP"
    port: 8600
  selector:
    app: "consul-server"
  type: "LoadBalancer"
  loadBalancerIP: ""
