---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "db"
  namespace: "default"
  labels:
    app: "db"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "db"
  template:
    metadata:
      labels:
        app: "db"
    spec:
      serviceAccountName: "consul-sa"
      containers:
      - name: "db"
        image: "whatsaranjit/k8s_connect:v1"
        imagePullPolicy: Always
        env:
        - name: port
          value: '8081'
      - name: "consul"
        image: "consul"
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "CONSUL_LOCAL_CONFIG"
          value:
            "{
              \"leave_on_terminate\": true,
              \"bind_addr\": \"$(MY_POD_IP)\",
              \"client_addr\": \"$(MY_POD_IP)\",
              \"retry_join\": [\"provider=k8s label_selector=\\\"app=consul-server\\\"\"],
              \"service\": {
                \"name\": \"db\",
                \"port\": 8081,
                \"checks\": [{
                  \"http\": \"http://localhost:8081/db\",
                  \"interval\": \"10s\",
                  \"timeout\": \"1s\"
                }],
                \"connect\": { \"proxy\": {} }
              }
            }"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "db"
spec:
  selector:
    name: "db"
  clusterIP: None
