---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "db"
  namespace: "default"
  labels:
    app: "db"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "db"
  template:
    metadata:
      labels:
        app: "db"
    spec:
      containers:
      - name: "db"
        image: "whatsaranjit/k8s_connect:v1"
        imagePullPolicy: Always
        env:
        - name: port
          value: '8082'
      - name: "consul"
        image: "consul"
        env:
        - name: CONSUL_SERVER
          valueFrom:
            configMapKeyRef:
              name: consul
              key: ip
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "CONSUL_LOCAL_CONFIG"
          value:
            "{
              \"leave_on_terminate\": true,
              \"bind_addr\": \"$(MY_POD_IP)\",
              \"client_addr\": \"$(MY_POD_IP)\",
              \"retry_join\": [\"$(CONSUL_SERVER)\"],
              \"service\": {
                \"name\": \"db\",
                \"port\": 8082,
                \"checks\": [{
                  \"http\": \"http://localhost:8082/db\",
                  \"interval\": \"10s\",
                  \"timeout\": \"1s\"
                }],
                \"connect\": { \"proxy\": {} }
              }
            }"
